-- CreateTable
CREATE TABLE "Pokemon" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "primaryType" TEXT NOT NULL,
    "secondaryType" TEXT,
    "isShiny" BOOLEAN NOT NULL DEFAULT false,
    "isShalpha" BOOLEAN NOT NULL DEFAULT false,
    "ED_Acier_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Acier_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Acier_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Acier_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Acier_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Combat_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Combat_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Combat_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Combat_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Combat_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Dragon_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Dragon_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Dragon_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Dragon_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Dragon_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Eau_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Eau_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Eau_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Eau_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Eau_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Feu_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Feu_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Feu_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Feu_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Feu_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Fée_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Fée_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Fée_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Fée_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Fée_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Glace_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Glace_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Glace_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Glace_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Glace_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Insecte_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Insecte_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Insecte_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Insecte_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Insecte_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Normal_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Normal_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Normal_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Normal_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Normal_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Plante_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Plante_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Plante_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Plante_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Plante_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Poison_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Poison_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Poison_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Poison_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Poison_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Psy_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Psy_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Psy_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Psy_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Psy_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Roche_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Roche_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Roche_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Roche_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Roche_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Sol_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Sol_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Sol_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Sol_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Sol_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Speciale_5" BOOLEAN NOT NULL DEFAULT false,
    "ED_Spectre_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Spectre_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Spectre_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Spectre_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Spectre_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Ténèbres_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Ténèbres_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Ténèbres_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Ténèbres_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Ténèbres_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Vol_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Vol_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Vol_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Vol_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Vol_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "ED_Électrik_1" BOOLEAN NOT NULL DEFAULT false,
    "ED_Électrik_2" BOOLEAN NOT NULL DEFAULT false,
    "ED_Électrik_3" BOOLEAN NOT NULL DEFAULT false,
    "ED_Électrik_4" BOOLEAN NOT NULL DEFAULT false,
    "ED_Électrik_5_Speciale" BOOLEAN NOT NULL DEFAULT false,
    "shinySpriteUrl" TEXT,
    "spriteUrl" TEXT,
    "nationalDexId" INTEGER,
    "regionalDexId" INTEGER,
    "nameEn" TEXT,
    "nameJa" TEXT,

    CONSTRAINT "Pokemon_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Pokemon_name_key" ON "Pokemon"("name");
